'
' Copyright (c) 2014 Han Hung
' 
' This program is free software; it is distributed under the terms
' of the GNU General Public License v3 as published by the Free
' Software Foundation.
'
' http://www.gnu.org/licenses/gpl-3.0.html
' 

Imports System.Text
Friend Class frmHelp

#Region " Event Handlers "
    Private Sub frmHelp_Load(sender As Object, e As EventArgs) Handles MyBase.Load
        LoadHelp()
    End Sub

    Private Sub btnOK_Click(sender As Object, e As EventArgs) Handles btnOK.Click
        Me.Close()
    End Sub

#End Region

#Region " Private Methods "

    Private Sub LoadHelp()
        Dim sTemp As New StringBuilder
        With sTemp
            .Append("The game of Sudoku is pretty simple.  The game is played on ")
            .Append("a 9 x 9 grid that is further subdivided into smaller 3 x 3 ")
            .Append("grids.  The game begins with some cells filled with numbers ")
            .Append("and some empty cells.")
            .AppendLine("")
            .AppendLine("")
            .Append("The object of the game is to fill each of the missing cells ")
            .Append("with the numbers 1 through 9 so that each row, column, and 3 x ")
            .Append("3 grid contains the same number only once.")
            .AppendLine("")
            .AppendLine("")
            .Append("Each puzzle generated by this program has one and only one ")
            .Append("solution.")
            .AppendLine("")
            .AppendLine("")
            .Append("To start the game, select a difficulty level.  A new game will ")
            .Append("be loaded.  The status bar at the bottom will indicate whether ")
            .Append("a game was successfully loaded or not.")
            .AppendLine("")
            .AppendLine("")
            .Append("To load another game, click the 'New Game' button.")
            .AppendLine("")
            .AppendLine("")
            .Append("To start the game, click the 'Start Game' button and the 9x9 ")
            .Append("board will be displayed.")
            .AppendLine("")
            .AppendLine("")
            .Append("To enter a number into a cell, click one of the blank cells.  A ")
            .Append("number pad will appear.  Click on one of the numbers to enter that ")
            .Append("value.")
            .AppendLine("")
            .AppendLine("")

            .Append("If the number is green, it means that the value entered is correct.  ")
            .Append("If it is red, then the number is incorrect.  Click the cell again ")
            .Append("to make the number pad reappear or click the button 'Clear Cell' to ")
            .Append("remove your answer.")

            .AppendLine("")
            .AppendLine("")
            .Append("To make the number pad disappear without entering a value, click the 'x' ")
            .Append("which is located in the upper right corner of the pad.")
            .AppendLine("")
            .AppendLine("")
            .Append("Good luck and enjoy the game!")
        End With
        txtHelp.Text = sTemp.ToString
        txtHelp.Select(0, 0)
    End Sub

#End Region

End Class